apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: pod-logs
    description: inspect pod logs of backstage and cockpit
    annotations:
        backstage.io/techdocs-ref: dir:.
        backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=backstage'         
spec:
    type: service
    lifecycle: production
    owner: guests
