apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: guests
  system: artist-engagement-portal
  definition:
    $text: ./feature.swagger.json
